---
title: "Emerald Pickups Analysis"
author: "David"
date: "2026-02-19"
output: html_document
---

## Setup

```{r setup}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(readxl)
library(dplyr)
library(lubridate)
library(janitor)
library(tidyr)
library(ggplot2)
library(scales)
```

## 1) Read pickups data

```{r read-pickups}
df_raw <- read_excel(
  "Meters Data 2024.xlsx",
  sheet = "Emerald Pickups",
  range = "A1:P50074"
) %>%
  clean_names()
```



```{r}
pickup_pa <-df_raw %>% 
  filter(state== "PA")
  
```






## 5) Read meter features and keep one row per customer

```{r read-meters}
meters <- read_excel(
  "Meters Data 2024.xlsx",
  sheet = "Combined Meter Data"
) %>%
  clean_names()
pa_meters <- meters %>%
  filter(state == "PA")

```





```{r}
library(readxl)
library(dplyr)

data <- read_excel("Service_Territory_2024.xlsx")

colnames(data)

pa_data <- data %>%
  filter(State == "PA")

pa_data <- pa_data %>% 
  clean_names()
```


```{r}
df_pa_2 <- pa_data %>%
  right_join(pa_meters, by = c("utility_number"), relationship = "many-to-one")

df_pa_2 <- pa_data %>%
  right_join(pa_meters, by = "utility_number", relationship = "many-to-one") %>%
  select(-ends_with(".y")) %>%
  rename_with(~ str_remove(., "\\.x$"))
```




```{r}
df_pa_full <- df_pa_2 %>%
 left_join(pickup_pa, by = c("emerald_customer_id" = "customer_id"), relationship = "many-to-many")

#Running this adds monthly pickup numbers for each emerald customer, however some customers will have multiple rows indicating seperate counties served but pickup per month sums across all counties for a customers note this issue also exists for current yearly pickups, however adding less rows 

```




```{r}
library(tidyverse)
library(janitor)
census <- read.csv("census_data.csv")
census <- census %>%
  clean_names() %>%     
  rename(
    State_County_FIPS = stcofips,
    total_pop = tot_pop,
    male_pop = male_pop,
    female_pop = female_pop,
    pop_under_5 = under_5_pop,
    pop_5_9 = x5_9_pop,
    pop_10_14 = x10_14_pop,
    pop_15_19 = x15_19_pop,
    pop_20_24 = x20_24_pop,
    pop_25_34 = x25_34_pop,
    pop_35_44 = x35_44_pop,
    pop_45_54 = x45_54_pop,
    pop_55_59 = x55_59_pop,
    pop_60_64 = x60_64_pop,
    pop_65_74 = x65_74_pop,
    pop_75_84 = x75_84_pop,
    pop_85_plus = x85_plus_pop,
    median_age = median_age,
    white_pop = white_pop,
    black_pop = black_pop,
    native_pop = native_pop,
    asian_pop = asian_pop,
    other_race_pop = other_race_pop,
    hispanic_latino_pop = hispanic_latino_pop,
    housing_units_total = total_housing_units,
    housing_units_occupied = occupied_housing_units,
    housing_units_owner = owner_occupied_housing_units,
    housing_units_renter = renter_occupied_housing_units
  )
```



```{r}
nri <- read_csv("NRI_COUNTY_Trimmed.csv") %>%
 mutate(
   GEOID = str_pad(STCOFIPS, width = 5, pad = "0")
  )

nri_model <- nri %>%
  select( 
    GEOID, STATEABBRV, COUNTY,
    CWAV_RISKS,
    CWAV_EVNTS, CWAV_AFREQ, CWAV_EXP_AREA,
    CWAV_EXPB, CWAV_EXPP, CWAV_EXPPE, CWAV_EXPT,
    SOVI_SCORE, SOVI_RATNG,
    ISTM_RISKS, WNTW_RISKS,
    BUILDVALUE, AGRIVALUE, AREA
  )

nri_model


```





```{r}
library(tidycensus)
library(dplyr)
library(stringr)
library(purrr)

YEAR <- 2024

# Helper: pull ACS wide and return county + state as separate fields
acs_county <- function(vars) {
  get_acs(
    geography = "county",
    variables = unname(vars),   # IMPORTANT: keeps raw codes as column names in wide output
    year = YEAR,
    survey = "acs5",
    output = "wide"
  ) %>%
    select(-matches("M$")) %>%
    transmute(
      county = str_remove(NAME, ",.*$"),
      state  = str_remove(NAME, "^.*?,\\s*"),
      across(ends_with("E"))
    )
}

# ---- Median year built ----
year_built <- acs_county("B25035_001") %>%
  transmute(county, state, median_year_built = B25035_001E)

# ---- Median rent ----
rent <- acs_county("B25064_001") %>%
  transmute(county, state, median_rent = B25064_001E)

# ---- Housing unit types (one/multi/mobile) ----
units <- acs_county(c(paste0("B25024_00", 1:9), "B25024_010", "B25024_011")) %>%
  transmute(
    county, state,
    one_unit_housing_pct =
      (B25024_002E + B25024_003E) / B25024_001E * 100,
    mobile_home_pct =
      B25024_010E / B25024_001E * 100,
    multi_unit_housing_pct =
      (B25024_004E + B25024_005E + B25024_006E +
         B25024_007E + B25024_008E + B25024_009E) / B25024_001E * 100
  )

# ---- Internet (no internet %) ----
internet <- acs_county(c("B28002_001", "B28002_013")) %>%
  transmute(
    county, state,
    no_internet_pct = B28002_013E / B28002_001E * 100
  )

# ---- Median household income ----
income <- acs_county("B19013_001") %>%
  transmute(county, state, median_income = B19013_001E)

# ---- Median home value ----
home_value <- acs_county("B25077_001") %>%
  transmute(county, state, median_home_value = B25077_001E)

# ---- Education (% for 25+ population) ----
edu_codes <- list(
  total_25_over = "B15003_001",
  less_than_hs  = paste0("B15003_", sprintf("%03d", 2:16)),
  hs_grad       = "B15003_017",
  some_college  = paste0("B15003_", sprintf("%03d", 18:21)),
  college_grad  = paste0("B15003_", sprintf("%03d", 22:25))
)

edu_raw <- acs_county(unlist(edu_codes))

education <- edu_raw %>%
  mutate(
    total_less_than_hs =
      rowSums(across(all_of(paste0(edu_codes$less_than_hs, "E"))), na.rm = TRUE),
    total_some_college =
      rowSums(across(all_of(paste0(edu_codes$some_college, "E"))), na.rm = TRUE),
    total_college_grad =
      rowSums(across(all_of(paste0(edu_codes$college_grad, "E"))), na.rm = TRUE),

    less_than_hs_pct = total_less_than_hs / B15003_001E * 100,
    hs_grad_pct      = B15003_017E / B15003_001E * 100,
    some_college_pct = total_some_college / B15003_001E * 100,
    college_grad_pct = total_college_grad / B15003_001E * 100
  ) %>%
  select(county, state, less_than_hs_pct, hs_grad_pct, some_college_pct, college_grad_pct)

# ---- Employment (% labor force, unemployment, armed forces) ----
employment <- acs_county(paste0("B23025_00", 1:7)) %>%
  transmute(
    county, state,
    labor_force_pct  = B23025_002E / B23025_001E * 100,
    unemployed_pct   = B23025_005E / B23025_003E * 100,
    armed_forces_pct = B23025_006E / B23025_002E * 100
  )

# ---- Health insurance (% uninsured) ----
noins_vars <- c(
  "B27001_005","B27001_008","B27001_011","B27001_014","B27001_017",
  "B27001_020","B27001_023","B27001_026","B27001_029",
  "B27001_033","B27001_036","B27001_039","B27001_042","B27001_045",
  "B27001_048","B27001_051","B27001_054","B27001_057"
)

health_raw <- acs_county(c("B27001_001", noins_vars))

health <- health_raw %>%
  transmute(
    county, state,
    uninsured_pct = rowSums(across(all_of(paste0(noins_vars, "E"))), na.rm = TRUE) / B27001_001E * 100
  )

# ---- Demographics + age buckets + race + housing occupancy/tenure ----
demo_vars <- c(
  TOT_POP   = "B01001_001",
  MALE_POP  = "B01001_002",
  FEMALE_POP= "B01001_026",

  # Male age cells
  M_U5="B01001_003", M_5_9="B01001_004", M_10_14="B01001_005", M_15_17="B01001_006",
  M_18_19="B01001_007", M_20="B01001_008", M_21="B01001_009", M_22_24="B01001_010",
  M_25_29="B01001_011", M_30_34="B01001_012", M_35_39="B01001_013", M_40_44="B01001_014",
  M_45_49="B01001_015", M_50_54="B01001_016", M_55_59="B01001_017", M_60_61="B01001_018",
  M_62_64="B01001_019", M_65_66="B01001_020", M_67_69="B01001_021", M_70_74="B01001_022",
  M_75_79="B01001_023", M_80_84="B01001_024", M_85PLUS="B01001_025",

  # Female age cells
  F_U5="B01001_027", F_5_9="B01001_028", F_10_14="B01001_029", F_15_17="B01001_030",
  F_18_19="B01001_031", F_20="B01001_032", F_21="B01001_033", F_22_24="B01001_034",
  F_25_29="B01001_035", F_30_34="B01001_036", F_35_39="B01001_037", F_40_44="B01001_038",
  F_45_49="B01001_039", F_50_54="B01001_040", F_55_59="B01001_041", F_60_61="B01001_042",
  F_62_64="B01001_043", F_65_66="B01001_044", F_67_69="B01001_045", F_70_74="B01001_046",
  F_75_79="B01001_047", F_80_84="B01001_048", F_85PLUS="B01001_049",

  MEDIAN_AGE = "B01002_001",

  WHITE_POP  = "B02001_002",
  BLACK_POP  = "B02001_003",
  HISPANIC_POP = "B03003_003",

  TOTAL_HOUSING_UNITS    = "B25001_001",
  OCCUPIED_HOUSING_UNITS = "B25002_002",
  OWNER_OCCUPIED         = "B25003_002",
  RENTER_OCCUPIED        = "B25003_003"
)

demo_raw <- acs_county(demo_vars)

demographics <- demo_raw %>%
  transmute(
    county, state,

    total_pop  = B01001_001E,
    median_age = B01002_001E,

    male_pct   = B01001_002E / B01001_001E * 100,
    female_pct = B01001_026E / B01001_001E * 100,

    age_0_17_pct =
      (B01001_003E + B01001_004E + B01001_005E + B01001_006E +
       B01001_027E + B01001_028E + B01001_029E + B01001_030E) / B01001_001E * 100,

    age_18_24_pct =
      (B01001_007E + B01001_008E + B01001_009E + B01001_010E +
       B01001_031E + B01001_032E + B01001_033E + B01001_034E) / B01001_001E * 100,

    age_25_34_pct =
      (B01001_011E + B01001_012E + B01001_035E + B01001_036E) / B01001_001E * 100,

    age_35_44_pct =
      (B01001_013E + B01001_014E + B01001_037E + B01001_038E) / B01001_001E * 100,

    age_45_54_pct =
      (B01001_015E + B01001_016E + B01001_039E + B01001_040E) / B01001_001E * 100,

    age_55_64_pct =
      (B01001_017E + B01001_018E + B01001_019E +
       B01001_041E + B01001_042E + B01001_043E) / B01001_001E * 100,

    age_65_plus_pct =
      (B01001_020E + B01001_021E + B01001_022E + B01001_023E + B01001_024E + B01001_025E +
       B01001_044E + B01001_045E + B01001_046E + B01001_047E + B01001_048E + B01001_049E) /
      B01001_001E * 100,

    white_pct    = B02001_002E / B01001_001E * 100,
    black_pct    = B02001_003E / B01001_001E * 100,
    hispanic_pct = B03003_003E / B01001_001E * 100,

    total_housing_units   = B25001_001E,
    occupied_housing_pct  = B25002_002E / B25001_001E * 100,
    owner_occupied_pct    = B25003_002E / B25001_001E * 100,
    renter_occupied_pct   = B25003_003E / B25001_001E * 100
  )

# ---- Combine into ONE county dataset ----
county_acs_2024 <- list(
  demographics,
  income,
  home_value,
  rent,
  year_built,
  units,
  internet,
  education,
  employment,
  health
) %>% reduce(left_join, by = c("county", "state"))




# Done:
# county_acs_2022 now contains one row per county with county + state as separate fields.

```



```{r}


pa_acs <- county_acs_2024 %>%
  filter(state == "Pennsylvania")

library(stringr)
library(dplyr)

df_pa_2 <- df_pa_2 %>%
  mutate(
    county = str_trim(county),
    county = ifelse(str_detect(county, "County$"),
                    county,
                    paste0(county, " County"))
  )

df_pa_acs <- df_pa_2 %>% 
  left_join(pa_acs, by = "county",relationship = "many-to-one")
```

